dist: xenial
language: python
python: 3.5

before_install:
- sudo apt-get install -y ruby ruby-dev rubygems build-essential libffi-dev devscripts
  libsystemd-dev
- sudo gem install -n /usr/local/bin --no-ri --no-rdoc fpm
addons:
  apt:
    update: true

install:
- pip install virtualenv sh plumbum

script:
-
- sudo `which python3` package/make-deb.py

deploy:
  provider: bintray
  file: "./package/descriptor.json"
  user:
    secure: dgFRNX7PqhV3GI4fzgnBuxjd4TIwuJLMYLIrvkOVxxHgW67yvoSP2NLkGhYbNA5klLw6UR1vi9A3RwbLmfeAG3BlWMNY6qVMpxhVagwZaUmIC28LfFsxFrGzrAiOpc1OLDFT4iweS0+HglOvNCnFncpAbP3gvMCvdFd8AbS/y1lWe+vRXXY4JWnE7X8kMgn91RDX9gQ3+ycF8UEJ0DVLDObrhbT+2mNirb5ikCNReOeDYUbYpSsnNlJmR3G8bi/wuDWhV3b1g54jGp7z9Igw/WeAiONmSprXP44D/Gswh2kryALu4F5mbsd38gsoa0U5CPaHbjCMvQnLfORN853qElJ+RQb2T/err3UQTRYgGjE1qzs1A6SHuAZSg+Npy3C6aZ+N0CfaJW7R41MG1ycfRG5Xvo/8yq6//6YBTjsSChu15FsN+ADPEGXutzP2FNXm8Lm8QWmLd7BF1c/XY7m1Ey8fU3ThrYdNCH396Xs7yPdJ+956NZztlGsuO3NkOcWz+kQsJXYTMyTwnA0QMGddMvgdUQhzjJQyuc+okDq3BTg/h08M2khL0CafbaELUFH0Z0m+DVF9LOWMFcK5JeWrc7cWd2Do3p22yfTXcVVEWI6eHfDo3UDnFXwKgDLP2T2auFGARoz8wQy3IOO7913uAjsRjG4q8LsZ4DKxcg2qUe8=
  key:
    secure: Q0Z/iiX14j7+6K55B5oYtROeRmHEhCI497noCE8D2iZX8nORXKdr+yWvS3q3ni0LmyswTYlh4WWvkxI/j7DGe2o71A+4vSOpxVllqQUU8Y+Nx/pBsCB93LPg/uv45YrRCfSPLbmznHn+dA60WnP8QFzamY1eOeYIZMc7n/HYi4CVyeBf5DZ16aSYbezr9d4GECYvpNB6KViRCFQf2OVJTKhqpupGvm6g0+UhXLkImwt3Ri9Gx69VXSGnrHgHWhS70KVWI3vFNtq13Chhyw2XQSuZvgabiOEh2xRmRgNRgthl1LZrbIuFt/1yCSiVwQnFbkNl3ZG6S4+VSxpyeRK35awlRG9aeW4dUf/nC1mwdgZJvqES1RqeUodTRcaP21ziK+dl1Y3JIm+e5cM1lJf5L53ZZsjxKNkbHy4JSjmZ+/QJ8drtdK2RB3dQ2nIizDVQDIJLL+IJ/Q4mKZGi9FfYhkZQtda/fFIN3VPLzEmxv5qN1xWLIHR0fEY5wS20kXLEYLTon8vmSchBJ2SYYvCTWFHtJSBr2KzUHupLbbqidx4TApaZBuI4rCDGu0Rac4NZDRyScsdqKwkpNNeL6N3Q1CIfhlHH++gPlSf8IErN6E6Rqvg4HWijJap48JGtfmBtX5yVfSF1X4ybHMFoOXvR8yeyFo9SmTy39qBEJAaqHTc=
  skip_cleanup: true
